"""add instruction to generations
Revision ID: 38a6b0503354
Revises: 791d942ace48
Create Date: 2026-07-15 04:25:21.124715
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision: str = '38a6b0503354'
down_revision: Union[str, Sequence[str], None] = '791d942ace48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generations', sa.Column('instruction', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###
def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generations', 'instruction')
    # ### end Alembic commands ###
